In [2]:
import numpy as np

In [2]:
a = np.array((1, 2))
b = np.array([(0, 2), (4, 3)])

a + b

array([[1, 4],
       [5, 5]])

In [3]:
(a + b).T

array([[1, 5],
       [4, 5]])

In [8]:
inside = lambda position_array: np.all(np.logical_and(position_array >= 0, position_array < 17), axis = 1)

In [10]:
inside(np.array([(0, 0), (13, 2), (-1, 5), (7, 17), (16, 16)]))

array([ True,  True, False, False,  True])