In [4]:
import numpy as np

In [23]:
test_features = np.array( \
    [[0, 2, 0, 1],
     [1, 1, 0, 2],
     [0, 0, 2, 0],
     [2, 1, 0, 1],
     [1, 2, 0, 0],
     [2, 0, 0, 0]]
)

In [35]:
sorted_features = np.sort(test_features, axis = 1)
print("Sorted features")
print(sorted_features)

Sorted features
[[0 0 1 2]
 [0 1 1 2]
 [0 0 0 2]
 [0 1 1 2]
 [0 0 1 2]
 [0 0 0 2]]


In [36]:
sorted_indices = np.argsort(test_features, axis = 1)
print("Sorted indices")
print(sorted_indices)

Sorted indices
[[0 2 3 1]
 [2 0 1 3]
 [0 1 3 2]
 [2 1 3 0]
 [2 3 0 1]
 [1 2 3 0]]


In [26]:
# Test if sort is random
equal = np.empty(100)
for i in range(100):
    sorted_indices  = np.argsort(test_features, axis = 1)
    sorted_indices2 = np.argsort(test_features, axis = 1)
    equal[i] = np.all(sorted_indices == sorted_indices2)
np.all(equal)
# If True then not random

True

In [27]:
# Does backtransformation work?
np.all(test_features == sorted_features[sorted_indices])

/var/folders/43/7lbyzcz55dz1yrwzhvb9dk9c0000gn/T/ipykernel_28977/2928762744.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  np.all(test_features == sorted_features[sorted_indices])


False

In [34]:
# Does backtransformation work like test_features == sorted_features[sorted_indices]?
print("restored  test")
restored_features = np.empty_like(test_features)
for i in range(len(test_features)):
    restored_features[i] = sorted_features[i][sorted_indices[i]]
    print(restored_features[i], test_features[i])
print("Same:", np.all(restored_features == test_features))
# If False then it doesn't work like that

restored  test
[0 1 2 0] [0 2 0 1]
[1 0 1 2] [1 1 0 2]
[0 0 2 0] [0 0 2 0]
[1 1 2 0] [2 1 0 1]
[1 2 0 0] [1 2 0 0]
[0 0 2 0] [2 0 0 0]
Same: False


In [38]:
# Does backtransformation work like this?
backtrafo_indices = np.argsort(sorted_indices)

print("restored  test")
restored_features = np.empty_like(test_features)
for i in range(len(test_features)):
    restored_features[i] = sorted_features[i][backtrafo_indices[i]]
    print(restored_features[i], test_features[i])
print("Same:", np.all(restored_features == test_features))
# If True then it does work like that

restored  test
[0 2 0 1] [0 2 0 1]
[1 1 0 2] [1 1 0 2]
[0 0 2 0] [0 0 2 0]
[2 1 0 1] [2 1 0 1]
[1 2 0 0] [1 2 0 0]
[2 0 0 0] [2 0 0 0]
Same: True
