In [2]:
import numpy as np
import pickle
import matplotlib.pyplot as plt

In [7]:
ACTIONS = ['UP', 'RIGHT', 'DOWN', 'LEFT', 'WAIT', 'BOMB']

print(ACTIONS.index('DOWN'))

2


In [35]:
file_name = "../agent_code/agent_vq10/model_vq10ch1.pt"
with open(file_name, "rb") as file:
    model = pickle.load(file)
    #plt.imshow(model.T)
    print(model)

[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [ -1.  -1.   1.  -1.  -1.  -1.]
 [  0.   0.   0.   0.   0.   0.]
 [ -2.   2.   2.   1.   1.   2.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  2.  -2.  -2.  -2.  -2.  -2.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [ -7.  -1.  -7.  -7.  -7.  -7.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0

In [28]:
test_array = np.ones((2,3))
np.savetxt('test_data.csv', test_array)

In [3]:
test_file = lambda x: f"test_log/test{x}.npy"
test_array = np.arange(100).reshape((10, 10))
for i, num in enumerate(test_array):
    with open(test_file(i), "wb") as file:
        np.save(file, num)

In [4]:
for i in range(10):
    print(np.load(test_file(i)))

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24 25 26 27 28 29]
[30 31 32 33 34 35 36 37 38 39]
[40 41 42 43 44 45 46 47 48 49]
[50 51 52 53 54 55 56 57 58 59]
[60 61 62 63 64 65 66 67 68 69]
[70 71 72 73 74 75 76 77 78 79]
[80 81 82 83 84 85 86 87 88 89]
[90 91 92 93 94 95 96 97 98 99]


In [7]:
np.load('../agent_code/agent_vq10/logs/Q_data/Q10.npy')

array([[  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [ 11.,  11.,  12.,  11.,   9.,  11.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [ 12.,  12.,  12.,  10.,  12.,  14.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [ -1.,  -1.,  -1.,  -1.,  -1.,  -1.],
       [ -2.,   8.,  -2.,  -2.,  -2.,  -2.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [ 12.,  12.,  12.,  -1.,  -1.,  -1.],
       [ -2.,  -2.,  11.,  -2.,  -2.,  -2.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [ -2.,  -2.,  11.,  -2.,  -2.,  12.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [ 12.,  11.,  -7.,  -7.,  -7.,  -7.],
       [ -