In [110]:
import numpy as np

In [111]:
empty_game_field = np.array(
    [[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
     [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
     [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
     [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
     [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
     [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
     [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
     [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
     [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
     [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
     [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
     [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
     [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
     [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
     [-1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1,  0, -1],
     [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
     [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],]
)

packed_game_field = np.array(
    [[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
     [-1,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  0, -1],
     [-1,  0, -1,  1, -1,  1, -1,  1, -1,  1, -1,  0, -1,  1, -1,  0, -1],
     [-1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  1, -1],
     [-1,  1, -1,  1, -1,  0, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1],
     [-1,  1,  1,  1,  1,  1,  0,  1,  0,  1,  0,  1,  0,  0,  1,  0, -1],
     [-1,  1, -1,  0, -1,  1, -1,  1, -1,  1, -1,  1, -1,  0, -1,  0, -1],
     [-1,  0,  1,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1, -1],
     [-1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  0, -1,  1, -1],
     [-1,  1,  1,  0,  1,  1,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1, -1],
     [-1,  1, -1,  1, -1,  1, -1,  0, -1,  1, -1,  1, -1,  1, -1,  0, -1],
     [-1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  1,  0, -1],
     [-1,  1, -1,  0, -1,  1, -1,  0, -1,  1, -1,  1, -1,  1, -1,  1, -1],
     [-1,  0,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  0,  1,  1,  0, -1],
     [-1,  0, -1,  1, -1,  0, -1,  0, -1,  0, -1,  0, -1,  1, -1,  0, -1],
     [-1,  0,  0,  1,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  0,  0, -1],
     [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],]
)

In [112]:
DIRECTIONS = np.array([(0, -1), (1, 0), (0, 1), (-1, 0)])   # UP, RIGHT, DOWN, LEFT

def time_to_reach (own_position, game_field):
    travel_times = np.full_like(game_field, 1000, dtype = int)
    travel_times[own_position] = 0
    #print(travel_times)
    
    #reachable    = np.full_like(game_field, False)
    #reachable[own_position] = True
    #print(reachable)

    # Breadth first search for travel times to all reachable spots
    frontier = [own_position]
    while len(frontier) > 0:
        current = frontier.pop(0)
        for dir in DIRECTIONS:
            neighbor = tuple(dir + np.array(current))
            #print(neighbor)
            if game_field[neighbor] == 0:   # If neighbor is a free field
                #reachable[neighbor] = True
                time = travel_times[current] + 1
                if travel_times[neighbor] > time:
                    travel_times[neighbor] = time
                    frontier.append(neighbor)
        #print(travel_times)

    return travel_times
        
    


In [51]:
%timeit time_to_reach((1,15), empty_game_field)

2.27 ms ± 48.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [114]:
%timeit time_to_reach((1,15), packed_game_field)

58.2 µs ± 2.37 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [116]:
time_to_reach((1,15), packed_game_field)

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
          2,   1,   0, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
        100, 100,   1, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
        1

In [122]:
time_to_reach((1,15), empty_game_field)

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
        100, 100, 100, 100],
       [100,  14,  13,  12,  11,  10,   9,   8,   7,   6,   5,   4,   3,
          2,   1,   0, 100],
       [100,  15, 100,  13, 100,  11, 100,   9, 100,   7, 100,   5, 100,
          3, 100,   1, 100],
       [100,  16,  15,  14,  13,  12,  11,  10,   9,   8,   7,   6,   5,
          4,   3,   2, 100],
       [100,  17, 100,  15, 100,  13, 100,  11, 100,   9, 100,   7, 100,
          5, 100,   3, 100],
       [100,  18,  17,  16,  15,  14,  13,  12,  11,  10,   9,   8,   7,
          6,   5,   4, 100],
       [100,  19, 100,  17, 100,  15, 100,  13, 100,  11, 100,   9, 100,
          7, 100,   5, 100],
       [100,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,   9,
          8,   7,   6, 100],
       [100,  21, 100,  19, 100,  17, 100,  15, 100,  13, 100,  11, 100,
          9, 100,   7, 100],
       [100,  22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,
         

In [113]:
BOMB_COOLDOWN_TIME = 7
number_of_crates = np.sum(empty_game_field == 1)

print(np.sum(empty_game_field == 1))
print(np.sum(packed_game_field == 1))


0
128


```python
# Idea for coin tracker:
training_setup():
    self.tracked_coins = []

game_events_occured():
    if game_state_old['coins'] != game_state_new['coins']:
        new_coins = [coin  for coin in game_state_old['coins']  if coin not in self.tracked_coins]
        self.tracked_coins += new_coins

TOTAL_COINS = 9   # Depends on scenario
number_of_hidden_coins = TOTAL_COINS - len(self.tracked_coins)
```

In [56]:
test_list = [1, 2]
test_list + [3, 4]

[1, 2, 3, 4]

In [104]:
COLS = ROWS = 17
BOMB_MASK = np.full((COLS * ROWS, COLS, ROWS), False)
BLAST = np.array([-3, -2, -1, 1, 2, 3])

x_inside = lambda x: x > 0 and x < COLS-1
y_inside = lambda y: y > 0 and y < ROWS-1

for x in range(1, COLS-1):
    for y in range(1, ROWS-1):
        if (x % 2 == 1 or y % 2 == 1):
            explosion_spots = [(x, y)]
            if x % 2 == 1:
                explosion_spots += [(x, y + b) for b in BLAST  if y_inside(y + b)]
            if y % 2 == 1:
                explosion_spots += [(x + b, y) for b in BLAST  if x_inside(x + b)]
            
            explosion_spots = np.array(explosion_spots).T
            #print(explosion_spots)
            index = x * COLS + y
            BOMB_MASK[index][explosion_spots[0], explosion_spots[1]] = True


In [105]:
print((BOMB_MASK*1)[-91])

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [107]:
# Idea for counting the destroyed crates

def number_of_destroyed_crates (game_field):
    crate_mask = game_field == 1

    return np.sum(np.logical_and(crate_mask, BOMB_MASK), axis = (1, 2)).reshape(crate_mask.shape)
    

In [121]:
%timeit number_of_destroyed_crates(empty_game_field)

93.4 µs ± 484 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [118]:
%timeit number_of_destroyed_crates(packed_game_field)


96.4 µs ± 2.42 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [117]:
number_of_destroyed_crates(packed_game_field)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0],
       [ 0,  4,  3,  6,  5,  8,  7, 10,  7, 10,  6,  7,  4,  6,  2,  3,
         0],
       [ 0,  3,  0,  4,  0,  4,  0,  5,  0,  5,  0,  4,  0,  3,  0,  2,
         0],
       [ 0,  6,  4,  9,  6, 10,  6, 12,  7, 12,  7, 10,  6,  7,  4,  4,
         0],
       [ 0,  4,  0,  5,  0,  6,  0,  7,  0,  6,  0,  6,  0,  4,  0,  3,
         0],
       [ 0,  8,  5,  9,  6, 10,  5, 10,  4,  8,  3,  8,  3,  6,  2,  5,
         0],
       [ 0,  6,  0,  4,  0,  6,  0,  6,  0,  6,  0,  7,  0,  4,  0,  5,
         0],
       [ 0,  9,  4,  9,  6, 12,  6, 10,  6, 12,  6, 12,  6,  9,  5,  7,
         0],
       [ 0,  6,  0,  5,  0,  7,  0,  5,  0,  6,  0,  7,  0,  3,  0,  3,
         0],
       [ 0,  8,  4,  8,  4,  9,  3,  8,  4,  9,  5, 12,  7,  9,  5,  7,
         0],
       [ 0,  5,  0,  5,  0,  7,  0,  4,  0,  6,  0,  7,  0,  5,  0,  4,
         0],
       [ 0,  8,  5, 10,  7, 12,  7,  9,  7, 12,  6, 11,  5,  9,  