In [1]:
import pickle
import numpy as np

In [2]:
file_name = "../../agent_code/agent_swq12/model_swq12.pt"
with open(file_name, "rb") as file:
    model = pickle.load(file)
    print(model)


[[    0.     0.     0.     0.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]
 [92826. 92826. 92827. 92827.]
 [92826. 92827. 92827. 92822.]
 [92817. 92812. 92827. 92827.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]
 [    0.     0.     0.     0.]]


In [3]:
def build_testlist_4D(d, D=4):
    """
    input:
        D = number of features
        d = number of possible elements for each feature
    output:
        lists of features in indexed order which is aimed for implicitly in "features_to_indices"
    """
    
    test_list = []
    
    for i in range(d):
        for j in range(i+1):
            for k in range(j+1):
                for l in range(k+1):
                    if l <= k and k <= j and j <= i:
                        test_list.append([l, k, j, i])
    
    return(test_list)

features = np.array(build_testlist_4D(3))

In [5]:
for i in range(len(features)):
    print(model[i], features[i])

[0. 0. 0. 0.] [0 0 0 0]
[0. 0. 0. 0.] [0 0 0 1]
[0. 0. 0. 0.] [0 0 1 1]
[0. 0. 0. 0.] [0 1 1 1]
[0. 0. 0. 0.] [1 1 1 1]
[0. 0. 0. 0.] [0 0 0 2]
[92826. 92826. 92827. 92827.] [0 0 1 2]
[92826. 92827. 92827. 92822.] [0 1 1 2]
[92817. 92812. 92827. 92827.] [1 1 1 2]
[0. 0. 0. 0.] [0 0 2 2]
[0. 0. 0. 0.] [0 1 2 2]
[0. 0. 0. 0.] [1 1 2 2]
[0. 0. 0. 0.] [0 2 2 2]
[0. 0. 0. 0.] [1 2 2 2]
[0. 0. 0. 0.] [2 2 2 2]
