In [43]:
import pickle
import numpy as np

In [44]:
file_name = "../../agent_code/agent_swq12/logs/Q_data/Q1.npy"
with open(file_name, "rb") as file:
    model =np.load(file)
    print(model)


[[ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [-0.19589041 -0.22105263  0.03877551  0.11944444]
 [-0.0972973  -0.04       -0.04375     0.072     ]
 [ 0.32222222  0.03928571  0.255       0.06470588]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]


In [3]:
def build_testlist_4D(d, D=4):
    """
    input:
        D = number of features
        d = number of possible elements for each feature
    output:
        lists of features in indexed order which is aimed for implicitly in "features_to_indices"
    """
    
    test_list = []
    
    for i in range(d):
        for j in range(i+1):
            for k in range(j+1):
                for l in range(k+1):
                    if l <= k and k <= j and j <= i:
                        test_list.append([l, k, j, i])
    
    return(test_list)

features = np.array(build_testlist_4D(3))

In [4]:
for i in range(len(features)):
    print(model[i], features[i])

[0. 0. 0. 0.] [0 0 0 0]
[0. 0. 0. 0.] [0 0 0 1]
[0. 0. 0. 0.] [0 0 1 1]
[0. 0. 0. 0.] [0 1 1 1]
[0. 0. 0. 0.] [1 1 1 1]
[0. 0. 0. 0.] [0 0 0 2]
[-1. -1.  0.  0.] [0 0 1 2]
[0. 0. 0. 0.] [0 1 1 2]
[0. 0. 0. 0.] [1 1 1 2]
[0. 0. 0. 0.] [0 0 2 2]
[0. 0. 0. 0.] [0 1 2 2]
[0. 0. 0. 0.] [1 1 2 2]
[0. 0. 0. 0.] [0 2 2 2]
[0. 0. 0. 0.] [1 2 2 2]
[0. 0. 0. 0.] [2 2 2 2]


In [9]:
liste = [1,2,3]
liste[len(liste)-1]

3

In [27]:
def mean_over_non_zero_elements(array):
    """
    Input: 1-dimensional np.array 
    Output: mean of array, neglecting non-zero entries of the array
    """
    return(np.sum(array) / np.count_nonzero(array))

A = np.ones((2,3,4)) 
A[1,0,0] = 0

B = np.apply_along_axis(mean_over_non_zero_elements, 2, A)
C = np.mean(A, axis = 2)

print(np.all(B == 1), np.all(C == 1))

True False
