In [7]:
import pickle
import numpy as np

In [8]:
file_name = "../../agent_code/agent_swq12/model_swq12.pt"
with open(file_name, "rb") as file:
    model = pickle.load(file)
    print(model)


[[   0.    0.    0.    0.]
 [   0.    0.    0.    0.]
 [   0.    0.    0.    0.]
 [   0.    0.    0.    0.]
 [   0.    0.    0.    0.]
 [   0.    0.    0.    0.]
 [8886. 8886. 8887. 8887.]
 [8887. 8887. 8887. 8887.]
 [8882. 8887. 8882. 8882.]
 [   0.    0.    0.    0.]
 [   0.    0.    0.    0.]
 [   0.    0.    0.    0.]
 [   0.    0.    0.    0.]
 [   0.    0.    0.    0.]
 [   0.    0.    0.    0.]]
